### ISSUE TITLE
Feature: Auto Update Max Input Token Limit

### ISSUE THREAD

**Issue by Anteemony** [Anteemony/RAG-Playground#12]
Add a feature to auto-update the maximum input token limit (`max_tokens_limit `) depending on the selected model.

Different models have different input token limits.

Currently the `max_tokens_limit` is set to 4000 currently i.e. regardless of the model, the input is truncated to 4000 tokens.

This allows users to have more flexibility on their queries being passed.

**Comment by martinoywa** [comment]
I think I just fixed this? https://github.com/Anteemony/RAG-Playground/pull/64
😅
