### ISSUE TITLE
Feature: User Custom Chunk Size

### ISSUE THREAD

**Issue by Anteemony** [Anteemony/RAG-Playground#29]
Create the option to update the chunk size

When the retriever performs vector similarity using the query,
Document chunks similar to the query are returned and used as the context.

In the querying process,
the chain calls `get_docs()` internally and asks the retriever to get the relevant documents 
and if `max_tokens_limit` is set, the chain's `_reduce_token_below_limit` 
repeatedly reduces the number of documents by 1 until 
the total documents tokens are less than the `max_tokens_limit` variable.

So if you set `k` earlier and the total tokens of the returned similar
document chunks combined are more than the max token limit, then one 
of them is going away! 

This process continues until the value of the summed tokens of the similar doc chunks is less 
than the `max_tokens_limit` value.
(Note: `k` = amount of documents to return, default=4)

Having a big chunk size leads to big document chunks found by the retriever.
So if you set a big chunk size, the chain's `_reduce_token_below_limit` removes 
one entire document chunk repeatedly until the summed total tokens of the similar doc chunks found
are less than the `max_tokens_limit`. This might lead to loss of essential context in cases like this.

Users should have the option to set the chunk size they prefer. (e.g a slider or text input)

Note: This note is for ConversationalRetrievalChain, but the logic still applies to similar implementations

Additional:
Perhaps a mechanism can exist to show recommended chunk size when the (`max_tokens_limit`) is updated by the user. We have k (i.e. number of documents to retrieve) and max token limit and chunk size. Perhaps some arithmetic can help with this feature.

**Comment by martinoywa** [comment]
Hi @Anteemony, I'd like to take on this.

**Comment by Anteemony** [comment]
Hello @martinoywa 

I'm assigning it to you now

**Comment by martinoywa** [comment]
Hi @Anteemony, I'm relatively new to LangChain.
I reviewed the docs and haven't encountered `RetrievalQA.from_chain_type(...)` that can set `max_token_limit`. How will the ability to set `chunk_size` be recommended? Will there be need to update the chain?

**Comment by Anteemony** [comment]
Hello, 

The project was started out with `ConversationalRetrievalChain`, and then moved to `RetrievalQA`, see details in #32 

In the docs, both `ConversationalRetrievalChain `and `RetrievalQA `are deprecated.
 
The `max_token_limit ` was mentioned because `ConversationalRetrievalChain` was the chain in use by the time.

The `max_token_limit` feature could be added directly to `RetrievalQA ` by creating a custom class that 
implements the `_reduce_token_below_limit` feature of `ConversationalRetrievalChain `

But all in all, perhaps the codebase should be updated to use the recommended chain, I believe that's `create_retrieval_chain`

Are you familiar with that? Do you also have any other approaches you have in mind?

**Comment by Anteemony** [comment]
Hey @martinoywa, Sorry, I'm just seeing your first paragraph.

Excuse my last question. Don't worry, I'm looking into the `create_retrieval_chain`.
It may or may not have have some if not all that we need.

I recommend you just wait till then, or just brainstorm the logic.
So that you don't end up having to redo your work. 

Sorry about any inconvenience. I'll try to get back to you hopefully before the end of the day

**Comment by martinoywa** [comment]
Hi @Anteemony, no worries. I'll also keep exploring. I believe this should make the process easier for both of us.

**Comment by Anteemony** [comment]
Hello, please take a look at #51
